# hyprlock.conf - Everforest Dark Medium

$font = ZedMono Nerd Font

general {
    hide_cursor = true
    grace = 0
    ignore_empty_input = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 4, linear
    animation = fadeOut, 1, 4, linear
    animation = inputFieldDots, 1, 2, linear
}

# ====================== BACKGROUND ======================
background {
    monitor =
    #path = screenshot          # usa screenshot da tela atual
    path = ~/Imagens/wallpapers-everforest/xtale_everforest.png  # ou um wallpaper fixo
    blur_passes = 3
    blur_size = 2
    noise = 0.0117
    contrast = 0.8913
    brightness = 0.8172
    vibrancy = 0.1686
    vibrancy_darkness = 0.0
    color = rgba(45, 53, 59, 1.0)   # bg0 #2D353B
}

# ====================== INPUT FIELD ======================
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.35
    dots_center = true
    dots_rounding = -1

    outer_color = rgba(167, 192, 128, 0.8)      # green #A7C080
    inner_color = rgba(45, 53, 59, 0.85)        # bg0
    font_color = rgba(211, 198, 170, 1.0)       # fg #D3C6AA
    placeholder_text = <span foreground="##859289">password...</span>
    fail_color = rgba(230, 126, 128, 0.9)       # red #E67E80
    fail_text = <span foreground="##E67E80">ERROR</span>
    check_color = rgba(167, 192, 128, 0.9)      # green
    fail_transition = 300

    fade_on_empty = true
    fade_timeout = 2000
    rounding = 2
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.4)
    shadow_boost = 1.2

    position = 0, -40
    halign = center
    valign = center
}

# ====================== CLOCK ======================
label {
    monitor =
    text = $TIME
    font_size = 85
    font_family = $font
    color = rgba(211, 198, 170, 1.0)            # fg
    position = 0, 180
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.5)
}

# ====================== DATE ======================
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d de %B"
    font_size = 22
    font_family = $font
    color = rgba(133, 146, 137, 1.0)            # grey1 #859289
    position = 0, 100
    halign = center
    valign = center
}

# ====================== USER ======================
label {
    monitor =
    text =   $USER
    font_size = 18
    font_family = $font
    color = rgba(167, 192, 128, 0.9)            # green
    position = 0, -100
    halign = center
    valign = center
}

# ====================== LAYOUT ======================
label {
    monitor =
    text = $LAYOUT
    font_size = 14
    font_family = $font
    color = rgba(122, 132, 120, 0.8)            # grey0
    position = 30, 30
    halign = left
    valign = bottom
}
