[colors]
# E-Ink Dark 
foreground=c2c2c2
background=333333

## Selection (selection_background e selection_foreground)
selection-background=545454

## Cores do Terminal (ANSI)
regular0=333333  # black
regular1=cccccc  # red
regular2=686868  # green
regular3=7c7c7c  # yellow
regular4=868686  # blue
regular5=5e5e5e  # magenta
regular6=b8b8b8  # cyan
regular7=a4a4a4  # white/black (color7 no Kitty)

bright0=a4a4a4   # bright black (color8 no Kitty)
bright1=cccccc   # bright red
bright2=686868   # bright green
bright3=7c7c7c   # bright yellow
bright4=868686   # bright blue
bright5=5e5e5e   # bright magenta
bright6=b8b8b8   # bright cyan
bright7=868686   # bright white (color15 no Kitty)
